<?php
// Copyright (c) 2026 TomTom Enterprises. Licensed under the MIT License (see LICENSE).
/**
 * PHPManager — per-account PHP-FPM pools + version switching
 */
if (!class_exists('VhostManager')) require_once __DIR__ . '/VhostManager.php';
require_once __DIR__ . '/Root.php';

class PHPManager {

    private static string $poolDir = '/etc/php/{ver}/fpm/pool.d';

    /** Pools are generated by the privileged helper from validated settings; it also reloads PHP-FPM. */
    public static function createPool(string $username, string $phpVer, array $settings = []): void {
        // the package's pool limits: how many PHP requests run at once, and the ceiling for memory_limit
        $lim = DB::getInstance()->fetchOne(
            "SELECT p.php_max_children AS kids, p.php_memory_mb AS mem FROM accounts a LEFT JOIN packages p ON p.id = a.package_id WHERE a.username = ?", [$username]);
        if ($lim && !empty($lim['kids'])) $settings['max_children']  = (int)$lim['kids'];
        if ($lim && !empty($lim['mem']))  $settings['memory_cap_mb'] = (int)$lim['mem'];
        Root::ok('php.pool.write', ['username' => $username, 'php_version' => $phpVer, 'settings' => $settings]);
    }

    public static function removePool(string $username): void {
        Root::run('php.pool.remove', ['username' => $username]);
    }

    public static function switchVersion(int $accountId, string $newVer): void {
        $db   = DB::getInstance();
        $acct = $db->fetchOne("SELECT * FROM accounts WHERE id = ?", [$accountId]);
        if (!$acct) throw new RuntimeException("Account not found");

        $oldVer = $acct['php_version'];
        if ($oldVer === $newVer) return;

        // Remove the old pool (every version), create the new one
        Root::run('php.pool.remove', ['username' => $acct['username']]);
        self::createPool($acct['username'], $newVer, self::currentSettings($accountId));

        // Update vhost to use new socket
        VhostManager::create($acct['username'], $acct['domain'], $acct['home_dir'] . '/public_html', $newVer);

        $db->execute("UPDATE accounts SET php_version = ? WHERE id = ?", [$newVer, $accountId]);
        $db->execute("UPDATE php_configs SET php_version = ?, updated_at = NOW() WHERE account_id = ?", [$newVer, $accountId]);
    }

    public static function updateConfig(int $accountId, array $cfg): void {
        $db   = DB::getInstance();
        $acct = $db->fetchOne("SELECT username, php_version FROM accounts WHERE id = ?", [$accountId]);
        if (!$acct) throw new RuntimeException("Account not found");

        $settings = self::currentSettings($accountId);
        foreach (['memory_limit', 'max_execution_time', 'upload_max_filesize', 'post_max_size'] as $key) {
            if (isset($cfg[$key])) $settings[$key] = $cfg[$key];
        }
        self::createPool($acct['username'], $acct['php_version'], $settings);

        $db->execute(
            "INSERT INTO php_configs (account_id, php_version, memory_limit, max_execution_time, upload_max_filesize, post_max_size, updated_at)
             VALUES (?,?,?,?,?,?,datetime('now'))
             ON CONFLICT(account_id) DO UPDATE SET php_version=excluded.php_version,
             memory_limit=excluded.memory_limit, max_execution_time=excluded.max_execution_time,
             upload_max_filesize=excluded.upload_max_filesize, post_max_size=excluded.post_max_size,
             updated_at=excluded.updated_at",
            [$accountId, $acct['php_version'], $cfg['memory_limit'] ?? '256M', $cfg['max_execution_time'] ?? 30,
             $cfg['upload_max_filesize'] ?? '64M', $cfg['post_max_size'] ?? '64M']
        );
    }

    public static function listExtensions(string $phpVer): array {
        $out = shell_exec("php{$phpVer} -m 2>/dev/null") ?: '';
        return array_values(array_filter(explode("\n", $out), fn($l) => $l && !str_starts_with($l, '[')));
    }

    /** The account's saved PHP limits (php_configs), used when its pool is regenerated. */
    public static function currentSettings(int $accountId): array {
        $row = DB::getInstance()->fetchOne("SELECT memory_limit, max_execution_time, upload_max_filesize, post_max_size FROM php_configs WHERE account_id = ?", [$accountId]);
        return $row ? array_filter($row, fn($v) => $v !== null && $v !== '') : [];
    }
}
