#!/bin/bash
# Copyright (c) 2026 TomTom Enterprises. Licensed under the MIT License (see LICENSE).
# Install the NovaCPX privileged helper and its sudoers file.
#
#   bash deploy/install-root-helper.sh              install /usr/local/sbin/novacpx-root + /etc/sudoers.d/novacpx-root
#                                                    (existing sudoers files keep working alongside)
#   bash deploy/install-root-helper.sh --lockdown   ALSO retire the old wildcard sudoers files and take the web user's
#                                                    write access away from system configuration directories
#
# Run as root. Safe to re-run. The helper itself is deploy/novacpx-root; the panel talks to it through panel/lib/Root.php.
set -euo pipefail

[ "$(id -u)" = 0 ] || { echo "run as root" >&2; exit 1; }
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCKDOWN=0; [ "${1:-}" = "--lockdown" ] && LOCKDOWN=1
PHP_BIN="$(command -v php8.3 || command -v php)"

"$PHP_BIN" -l "$SRC/novacpx-root" >/dev/null || { echo "novacpx-root has a syntax error" >&2; exit 1; }

# ── the helper ────────────────────────────────────────────────────────────────
install -d -m 0755 /usr/local/sbin /etc/novacpx
install -d -m 0700 /var/lib/novacpx-root
install -o root -g root -m 0755 "$SRC/novacpx-root" /usr/local/sbin/novacpx-root.new
mv -f /usr/local/sbin/novacpx-root.new /usr/local/sbin/novacpx-root
# PHP CLI must be where the shebang says
[ -x /usr/bin/php ] || ln -s "$PHP_BIN" /usr/bin/php

# ── sudoers: the helper, plus a few commands whose arguments are fixed ───────
UNITS="apache2 nginx lighttpd caddy mysql mariadb postgresql postfix dovecot opendkim rspamd proftpd vsftpd pure-ftpd named bind9 pdns nsd fail2ban docker php7.4-fpm php8.0-fpm php8.1-fpm php8.2-fpm php8.3-fpm php8.4-fpm"
ACTIONS="start stop restart reload enable disable is-active is-enabled status"
TMP="$(mktemp)"
{
  echo "# NovaCPX: the web panel (www-data) may run ONE privileged program (validated, parameterised), plus a few fixed commands."
  echo "# Generated by deploy/install-root-helper.sh - do not edit; re-run the script."
  echo "Defaults:www-data !requiretty"
  echo "www-data ALL=(root) NOPASSWD: /usr/local/sbin/novacpx-root"
  echo "# fixed arguments only"
  echo "www-data ALL=(root) NOPASSWD: /usr/sbin/nginx -t, /usr/bin/nginx -t, /usr/sbin/postqueue -f, /usr/sbin/rndc reload"
  echo "# firewall rules (ufw cannot execute anything; its rules are the panel's firewall page)"
  echo "www-data ALL=(root) NOPASSWD: /usr/sbin/ufw status, /usr/sbin/ufw status verbose, /usr/sbin/ufw status numbered"
  echo "www-data ALL=(root) NOPASSWD: /usr/sbin/ufw allow *, /usr/sbin/ufw deny *, /usr/sbin/ufw delete *, /usr/sbin/ufw logging *"
  echo "www-data ALL=(root) NOPASSWD: /usr/sbin/ufw reload, /usr/sbin/ufw enable, /usr/sbin/ufw disable, /usr/sbin/ufw --force enable, /usr/sbin/ufw --force disable"
  echo "# service control for named units only"
  for u in $UNITS; do
    for a in $ACTIONS; do
      echo "www-data ALL=(root) NOPASSWD: /usr/bin/systemctl $a $u, /bin/systemctl $a $u"
    done
  done
} > "$TMP"
visudo -cf "$TMP" >/dev/null || { echo "generated sudoers file failed visudo" >&2; rm -f "$TMP"; exit 1; }
install -o root -g root -m 0440 "$TMP" /etc/sudoers.d/novacpx-root
rm -f "$TMP"
echo "installed /usr/local/sbin/novacpx-root and /etc/sudoers.d/novacpx-root"

[ "$LOCKDOWN" = 1 ] || { echo "(run again with --lockdown to retire the old wildcard sudoers files and lock the config directories)"; exit 0; }

# ── lockdown ─────────────────────────────────────────────────────────────────
BK="/root/novacpx-sudoers-backup-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BK"
for f in novacpx novacpx-firewall novacpx-panel novacpx-services; do
  [ -f "/etc/sudoers.d/$f" ] && { cp -p "/etc/sudoers.d/$f" "$BK/"; rm -f "/etc/sudoers.d/$f"; echo "retired /etc/sudoers.d/$f (copy in $BK)"; }
done
visudo -c >/dev/null

# Configuration the helper now owns must not be writable by the web user.
lock() { [ -e "$1" ] && chown -h root:root "$1" && chmod "$2" "$1" || true; }
for d in /etc/nginx/sites-available /etc/nginx/sites-enabled /etc/apache2/sites-available; do
  [ -d "$d" ] || continue
  lock "$d" 0755
  for f in "$d"/novacpx-* "$d"/*.conf; do [ -e "$f" ] || [ -L "$f" ] || continue; chown -h root:root "$f"; [ -L "$f" ] || chmod 0644 "$f"; done
done
lock /etc/fail2ban/jail.local 0644
if [ -d /etc/bind/novacpx-zones ]; then
  chown root:bind /etc/bind/novacpx-zones; chmod 0755 /etc/bind/novacpx-zones
  for f in /etc/bind/novacpx-zones/*; do [ -e "$f" ] && { chown root:bind "$f"; chmod 0644 "$f"; }; done
fi
[ -e /etc/bind/named.conf.novacpx ] && { chown root:bind /etc/bind/named.conf.novacpx; chmod 0644 /etc/bind/named.conf.novacpx; }
# docker group membership is root-equivalent; all docker work goes through the helper now
if getent group docker | grep -qw www-data; then gpasswd -d www-data docker >/dev/null && echo "removed www-data from the docker group"; fi
echo "lockdown complete"
